/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function PatientDashboard() {
  return (
    <div className="justify-between items-center shadow-[0px_4px_0px_-5px_rgba(39,42,44,0.10)] flex flex-col px-5" style={{ background: "linear-gradient(to bottom, #0000ff, #0000cc)" }}>
      <header className="max-w-[1244px] justify-between items-start self-center flex w-full gap-5 my-4 pr-3 max-md:max-w-full max-md:flex-wrap">
        <img
          loading="lazy"
          srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/41cdad94-8a3e-4dc7-bde8-a2a1999728d8?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/41cdad94-8a3e-4dc7-bde8-a2a1999728d8?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/41cdad94-8a3e-4dc7-bde8-a2a1999728d8?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/41cdad94-8a3e-4dc7-bde8-a2a1999728d8?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/41cdad94-8a3e-4dc7-bde8-a2a1999728d8?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/41cdad94-8a3e-4dc7-bde8-a2a1999728d8?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/41cdad94-8a3e-4dc7-bde8-a2a1999728d8?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/41cdad94-8a3e-4dc7-bde8-a2a1999728d8?apiKey=f65fc86a34044c00b391ca36f8445cb5&"className="aspect-[4.74] object-cover object-center w-[180px] justify-center items-center overflow-hidden self-center shrink-0 my-auto"
          alt="Logo"
        />
        <nav className="items-start self-stretch flex w-[570px] max-w-full justify-between gap-5 py-2 max-md:flex-wrap max-md:justify-center">
          <a href="#" className="text-white text-sm leading-5 self-center my-auto">
            Patient Cases
          </a>
          <a href="#" className="text-white text-sm leading-5 self-center w-[121px] my-auto">
            Case Consensuses
          </a>
          <a href="#" className="text-white text-sm leading-5 self-center my-auto">
            Submit
          </a>
          <a href="#" className="text-white text-sm leading-5 self-center my-auto">
            Resources
          </a>
          <div className="items-start rounded self-stretch flex justify-between gap-2">
            <div className="items-center self-stretch flex flex-col">
              <img
                loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/f5a78efc-f28e-4700-8f71-18f83de7d362?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/f5a78efc-f28e-4700-8f71-18f83de7d362?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/f5a78efc-f28e-4700-8f71-18f83de7d362?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/f5a78efc-f28e-4700-8f71-18f83de7d362?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/f5a78efc-f28e-4700-8f71-18f83de7d362?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/f5a78efc-f28e-4700-8f71-18f83de7d362?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/f5a78efc-f28e-4700-8f71-18f83de7d362?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/f5a78efc-f28e-4700-8f71-18f83de7d362?apiKey=f65fc86a34044c00b391ca36f8445cb5&"className="aspect-square object-cover object-center w-full fill-white overflow-hidden self-stretch grow"
                alt="Profile Picture"
              />
            </div>
            <div className="items-start self-center flex gap-1 my-auto">
              <div className="text-white text-sm leading-5 self-stretch">Leeza Sticco</div>
              <img
                loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/a4066d5e-07dd-45ec-906e-2e9dd70ea967?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/a4066d5e-07dd-45ec-906e-2e9dd70ea967?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/a4066d5e-07dd-45ec-906e-2e9dd70ea967?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/a4066d5e-07dd-45ec-906e-2e9dd70ea967?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/a4066d5e-07dd-45ec-906e-2e9dd70ea967?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/a4066d5e-07dd-45ec-906e-2e9dd70ea967?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/a4066d5e-07dd-45ec-906e-2e9dd70ea967?apiKey=f65fc86a34044c00b391ca36f8445cb5&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/a4066d5e-07dd-45ec-906e-2e9dd70ea967?apiKey=f65fc86a34044c00b391ca36f8445cb5&"className="aspect-[0.73] object-cover object-center w-[11px] overflow-hidden self-center shrink-0 my-auto"
                alt="Notification Icon"
              />
            </div>
          </div>
        </nav>
      </header>
    </div>
  );
}